name: Cleanup All Workflow Runs

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Delete all workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_by_state_pattern: 'ALL'
          delete_run_by_conclusion_pattern: 'ALL'
